services:
  caddy:
    container_name: caddy
    image: caddy:2
    networks:
      - web
    ports:
      - "443:443/tcp"
      - "80:80/tcp"
    restart: unless-stopped
    volumes:
      - ${PWD}/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - django-docker_media:/django-docker/media  # Volume partagé avec Django
      - django-docker_static:/django-docker/staticfiles  # Volume partagé avec Django
    working_dir: /srv

  web:
    container_name: web
    hostname: web
    build:
      context: "."  # Utilise le Dockerfile dans le répertoire courant
    networks:
      - web
    ports:
      - "8000:8000"  # Expose le port Django
    restart: unless-stopped
    volumes:
      - ".:/app"  # Monte le code source
      - "${PWD}/docker-data/sqlite:/app/db"  # Pour stocker la base SQLite
      - "django-docker_static:/app/staticfiles"  # Correspond à STATIC_ROOT dans Django

  dhcp:
    container_name: dhcp
    hostname: dhcp
    build:
      context: "."
      dockerfile: Dockerfile.dhcp
    restart: unless-stopped
    privileged: true  # Nécessaire pour sudo et les opérations DHCP
    volumes:
      - ".:/app"
      - "${PWD}/docker-data/sqlite:/app/db"  # Partage la même base SQLite

volumes:
  caddy_data: 
  caddy_config:
  django-docker_media:
  django-docker_static:

networks:
  web:
    driver: bridge
